/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aispeech_patch_PathUtil */

#ifndef _Included_com_aispeech_patch_PathUtil
#define _Included_com_aispeech_patch_PathUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aispeech_patch_PathUtil
 * Method:    patch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_aispeech_patch_PathUtil_patch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
