/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aispeech_diff_DiffUtil */

#ifndef _Included_com_aispeech_diff_DiffUtil
#define _Included_com_aispeech_diff_DiffUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aispeech_diff_DiffUtil
 * Method:    diff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_aispeech_diff_DiffUtil_diff
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
